name: Nick Stein
title: Software Engineer
phone: (617) 448-1192
city: Arlington, MA
email: nick@nickstein.net
github: nlwstein
linkedin: nlwstein
profile: 
  title: Profile
  description: Enthusiastic, highly motivated, and empathetic technology team leader and software engineer who is passionate about converting complex concepts into functional code.
skills: 
  title: Main Technical Skills
  entries: 
  - title: Backend Software Engineering
    description: My passion is developing the systems that the end user rarely interacts with directly, but absolutely must be in place (and function reliably enough) for them to have a satisfactory experience. Most of my experience has been with the C#, PHP, and JavaScript (Node, browser, and proprietary server-side scripting) languages. Of course, if the feature absolutely requires the use of AutoHotkey scripting, then you unfortunately have to use it, regardless of preference.
  - title: Database Design &amp; Integration
    description: I have also used both SQL-based and non-SQL-based collection type databases, both in design of the database and in access through an application, utilizing ORMs, or some other sane data access layer. I have used MySQL / MariaDB, MongoDB, and HPE Vertica.
  - title: Project Management
    description: From a project management standpoint, most of my experience has been with the Agile development methodology, using the Atlassian tools (BitBucket, JIRA, Confluence) with CD implemented through Bamboo, Jenkins or equivalent.
experience: 
  - name: SmarterTravel
    location: Cambridge, MA
    positions: 
    - name: Senior Software Engineer
      start: July 2021
      end: September 2022
      details: 
        - Built and maintained software features for an email pipeline capable of sending over 50 million messages per day on a Python / Kubernetes / Kafka / Redshift stack
        - Provided Ops for multiple business units, including maintenance and R&D for shared services, an on-call schedule, developing custom alarms in Nagios and Loki
        - Automated a large number of builds for projects on GitHub Actions
  - name: Trellis
    location: Malden, MA
    positions: 
    - name: Software Architect
      start: July 2020
      end: July 2021
      details: 
      - Built and maintained tooling for automating developer time tracking and client billing
      - Assisted engineering teams with spikes and design documentation for novel projects (such as headless e-commerce)
    - name: Director of Engineering
      start: October 2018
      end: July 2020
      details: 
      - Facilitated technical escalations from the Tech Leads and Project Management
      - Assisted the Project Management team with understanding the unique skills of each developer to help assign the right team members to their projects
      - Worked to get IC developers to 80% billable and Tech Leads to 65% billable consistently every week
      - Managed the entire backend engineering team, conducting 1x1s, performance reviews and other managerial functions for a team of 15+ full time engineers and contractors
    - name: Lead Senior Software Engineer
      start: July 2018
      end: October 2018
      details: 
      - Team Lead for a highly effective software engineering team with several direct reports
      - Software Engineering mentor and general Linux/Unix resource for junior developers
      - Built several applications to automate internal workflows, integrating tools like Google Sheets and JIRA to generate reports
    - name: Senior Software Engineer
      start: April 2018
      end: July 2018
      details: 
      - Architected and built frontend applications using Vue.js that pull data via custom WordPress APIs
      - Architected and built integrations with third-party services like point-of-sale and product information management platforms
      - Created CI/CD pipelines on various cloud platforms (Bitbucket Pipelines, Codeship, etc.) to automate deployments
    - name: Software Engineer
      start: September 2017
      end: April 2018
      details: 
      - Individual Contributor on many Magento 1 and Magento 2 client projects
      - Created a highly flexible, admin configurable, SVG-manipulation based frontend application that allows a user to heavily customize a product in Magento 2
      - Integrated PACE Anti-Piracy SDK into Magento 2 so that a client's checkout flow could seamlessly deploy licenses to iLok users
  - name: GSN Games (Game Show Network)
    location: Boston, MA
    positions: 
    - name: Software Engineer, Monetization
      start: April 2016
      end: September 2017
      details: 
      - Built new features for, and maintained existing ones, on an abstraction layer for Unity that controls multiple native video advertising SDKs
      - Created a solution for integrating a native survey provider into Unity without leveraging their Android / iOS SDKs
      - Created a build script that generated and built an Android Gradle project on Unity 5.3
      - Created an Android (Java) plugin to marshall data between a native advertising plugin and Unity
  - name: OYO Sports
    location: Acton, MA
    positions: 
    - name: Junior Software Engineer
      start: July 2014
      end: March 2016
      details:
      - Delivered a Magento-based ecommerce solution with a small team under a tight deadline
      - Created a distributed graphics automation pipeline leveraging C#, Python, and JavaScript which was used to create multiple product lines consisting of more than 100 SKUs each
      - Built a centralized API (Silex) for all of OYO Sports' online infrastructure
      - Worked with AWS, Ansible
education: B.S. Computer Information Technology | Champlain College, 2013
